version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sharanubuntu
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pmdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://sharanubuntu:admin@db:5432/pmdb
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./personalmanager
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
